module.exports = {
	theme: {
		extend: {
			colors: {
				'scrim': 'rgb(var(--md-token-scrim) / <alpha-value>)',
				'shadow': 'rgb(var(--md-token-shadow) / <alpha-value>)',
				'outline': 'rgb(var(--md-token-outline) / <alpha-value>)',
				'outline-variant': 'rgb(var(--md-token-outline-variant) / <alpha-value>)',
				'background': 'rgb(var(--md-token-background) / <alpha-value>)',
				'background-on': 'rgb(var(--md-token-background-on) / <alpha-value>)',

				'primary': {
					DEFAULT: 'rgb(var(--md-token-primary) / <alpha-value>)',
					'container': 'rgb(var(--md-token-primary-container) / <alpha-value>)',
					'on': 'rgb(var(--md-token-primary-on) / <alpha-value>)',
					'container-on': 'rgb(var(--md-token-primary-container-on) / <alpha-value>)',
					'inverse': 'rgb(var(--md-token-primary-inverse) / <alpha-value>)',
					'fixed': 'rgb(var(--md-token-primary-fixed) / <alpha-value>)',
					'fixed-dim': 'rgb(var(--md-token-primary-fixed-dim) / <alpha-value>)',
					'fixed-on': 'rgb(var(--md-token-primary-fixed-on) / <alpha-value>)',
					'fixed-on-variant': 'rgb(var(--md-token-primary-fixed-on-variant) / <alpha-value>)',
				},

				'secondary': {
					DEFAULT: 'rgb(var(--md-token-secondary) / <alpha-value>)',
					'container': 'rgb(var(--md-token-secondary-container) / <alpha-value>)',
					'on': 'rgb(var(--md-token-secondary-on) / <alpha-value>)',
					'container-on': 'rgb(var(--md-token-secondary-container-on) / <alpha-value>)',
					'inverse': 'rgb(var(--md-token-secondary-inverse) / <alpha-value>)',
					'fixed': 'rgb(var(--md-token-secondary-fixed) / <alpha-value>)',
					'fixed-dim': 'rgb(var(--md-token-secondary-fixed-dim) / <alpha-value>)',
					'fixed-on': 'rgb(var(--md-token-secondary-fixed-on) / <alpha-value>)',
					'fixed-on-variant': 'rgb(var(--md-token-secondary-fixed-on-variant) / <alpha-value>)',
				},

				'tertiary': {
					DEFAULT: 'rgb(var(--md-token-tertiary) / <alpha-value>)',
					'container': 'rgb(var(--md-token-tertiary-container) / <alpha-value>)',
					'on': 'rgb(var(--md-token-tertiary-on) / <alpha-value>)',
					'container-on': 'rgb(var(--md-token-tertiary-container-on) / <alpha-value>)',
					'inverse': 'rgb(var(--md-token-tertiary-inverse) / <alpha-value>)',
					'fixed': 'rgb(var(--md-token-tertiary-fixed) / <alpha-value>)',
					'fixed-dim': 'rgb(var(--md-token-tertiary-fixed-dim) / <alpha-value>)',
					'fixed-on': 'rgb(var(--md-token-tertiary-fixed-on) / <alpha-value>)',
					'fixed-on-variant': 'rgb(var(--md-token-tertiary-fixed-on-variant) / <alpha-value>)',
				},

				'error': {
					DEFAULT: 'rgb(var(--md-token-error) / <alpha-value>)',
					'container': 'rgb(var(--md-token-error-container) / <alpha-value>)',
					'on': 'rgb(var(--md-token-error-on) / <alpha-value>)',
					'container-on': 'rgb(var(--md-token-error-container-on) / <alpha-value>)',
				},

				'surface': {
					DEFAULT: 'rgb(var(--md-token-surface) / <alpha-value>)',
					'variant': 'rgb(var(--md-token-surface-variant) / <alpha-value>)',
					'on': 'rgb(var(--md-token-surface-on) / <alpha-value>)',
					'variant-on': 'rgb(var(--md-token-surface-variant-on) / <alpha-value>)',
					'inverse': 'rgb(var(--md-token-surface-inverse) / <alpha-value>)',
					'inverse-on': 'rgb(var(--md-token-surface-inverse-on) / <alpha-value>)',
					'tint': 'rgb(var(--md-token-surface-tint) / <alpha-value>)',
					'dim': 'rgb(var(--md-token-surface-dim) / <alpha-value>)',
					'bright': 'rgb(var(--md-token-surface-bright) / <alpha-value>)',
					'container-lowest': 'rgb(var(--md-token-surface-container-lowest) / <alpha-value>)',
					'container-low': 'rgb(var(--md-token-surface-container-low) / <alpha-value>)',
					'container': 'rgb(var(--md-token-surface-container) / <alpha-value>)',
					'container-high': 'rgb(var(--md-token-surface-container-high) / <alpha-value>)',
					'container-highest': 'rgb(var(--md-token-surface-container-highest) / <alpha-value>)',
				},

				'palette-primary': {
					0: 'rgb(var(--md-ref-palette-primary0) / <alpha-value>)',
					10: 'rgb(var(--md-ref-palette-primary10) / <alpha-value>)',
					20: 'rgb(var(--md-ref-palette-primary20) / <alpha-value>)',
					30: 'rgb(var(--md-ref-palette-primary30) / <alpha-value>)',
					40: 'rgb(var(--md-ref-palette-primary40) / <alpha-value>)',
					50: 'rgb(var(--md-ref-palette-primary50) / <alpha-value>)',
					60: 'rgb(var(--md-ref-palette-primary60) / <alpha-value>)',
					70: 'rgb(var(--md-ref-palette-primary70) / <alpha-value>)',
					80: 'rgb(var(--md-ref-palette-primary80) / <alpha-value>)',
					90: 'rgb(var(--md-ref-palette-primary90) / <alpha-value>)',
					95: 'rgb(var(--md-ref-palette-primary95) / <alpha-value>)',
					99: 'rgb(var(--md-ref-palette-primary99) / <alpha-value>)',
					100: 'rgb(var(--md-ref-palette-primary100) / <alpha-value>)',
				},

				'palette-secondary': {
					0: 'rgb(var(--md-ref-palette-secondary0) / <alpha-value>)',
					10: 'rgb(var(--md-ref-palette-secondary10) / <alpha-value>)',
					20: 'rgb(var(--md-ref-palette-secondary20) / <alpha-value>)',
					30: 'rgb(var(--md-ref-palette-secondary30) / <alpha-value>)',
					40: 'rgb(var(--md-ref-palette-secondary40) / <alpha-value>)',
					50: 'rgb(var(--md-ref-palette-secondary50) / <alpha-value>)',
					60: 'rgb(var(--md-ref-palette-secondary60) / <alpha-value>)',
					70: 'rgb(var(--md-ref-palette-secondary70) / <alpha-value>)',
					80: 'rgb(var(--md-ref-palette-secondary80) / <alpha-value>)',
					90: 'rgb(var(--md-ref-palette-secondary90) / <alpha-value>)',
					95: 'rgb(var(--md-ref-palette-secondary95) / <alpha-value>)',
					99: 'rgb(var(--md-ref-palette-secondary99) / <alpha-value>)',
					100: 'rgb(var(--md-ref-palette-secondary100) / <alpha-value>)',
				},

				'palette-tertiary': {
					0: 'rgb(var(--md-ref-palette-tertiary0) / <alpha-value>)',
					10: 'rgb(var(--md-ref-palette-tertiary10) / <alpha-value>)',
					20: 'rgb(var(--md-ref-palette-tertiary20) / <alpha-value>)',
					30: 'rgb(var(--md-ref-palette-tertiary30) / <alpha-value>)',
					40: 'rgb(var(--md-ref-palette-tertiary40) / <alpha-value>)',
					50: 'rgb(var(--md-ref-palette-tertiary50) / <alpha-value>)',
					60: 'rgb(var(--md-ref-palette-tertiary60) / <alpha-value>)',
					70: 'rgb(var(--md-ref-palette-tertiary70) / <alpha-value>)',
					80: 'rgb(var(--md-ref-palette-tertiary80) / <alpha-value>)',
					90: 'rgb(var(--md-ref-palette-tertiary90) / <alpha-value>)',
					95: 'rgb(var(--md-ref-palette-tertiary95) / <alpha-value>)',
					99: 'rgb(var(--md-ref-palette-tertiary99) / <alpha-value>)',
					100: 'rgb(var(--md-ref-palette-tertiary100) / <alpha-value>)',
				},

				'palette-error': {
					0: 'rgb(var(--md-ref-palette-error0) / <alpha-value>)',
					10: 'rgb(var(--md-ref-palette-error10) / <alpha-value>)',
					20: 'rgb(var(--md-ref-palette-error20) / <alpha-value>)',
					30: 'rgb(var(--md-ref-palette-error30) / <alpha-value>)',
					40: 'rgb(var(--md-ref-palette-error40) / <alpha-value>)',
					50: 'rgb(var(--md-ref-palette-error50) / <alpha-value>)',
					60: 'rgb(var(--md-ref-palette-error60) / <alpha-value>)',
					70: 'rgb(var(--md-ref-palette-error70) / <alpha-value>)',
					80: 'rgb(var(--md-ref-palette-error80) / <alpha-value>)',
					90: 'rgb(var(--md-ref-palette-error90) / <alpha-value>)',
					95: 'rgb(var(--md-ref-palette-error95) / <alpha-value>)',
					99: 'rgb(var(--md-ref-palette-error99) / <alpha-value>)',
					100: 'rgb(var(--md-ref-palette-error100) / <alpha-value>)',
				},

				'palette-neutral': {
					0: 'rgb(var(--md-ref-palette-neutral0) / <alpha-value>)',
					10: 'rgb(var(--md-ref-palette-neutral10) / <alpha-value>)',
					20: 'rgb(var(--md-ref-palette-neutral20) / <alpha-value>)',
					30: 'rgb(var(--md-ref-palette-neutral30) / <alpha-value>)',
					40: 'rgb(var(--md-ref-palette-neutral40) / <alpha-value>)',
					50: 'rgb(var(--md-ref-palette-neutral50) / <alpha-value>)',
					60: 'rgb(var(--md-ref-palette-neutral60) / <alpha-value>)',
					70: 'rgb(var(--md-ref-palette-neutral70) / <alpha-value>)',
					80: 'rgb(var(--md-ref-palette-neutral80) / <alpha-value>)',
					90: 'rgb(var(--md-ref-palette-neutral90) / <alpha-value>)',
					95: 'rgb(var(--md-ref-palette-neutral95) / <alpha-value>)',
					99: 'rgb(var(--md-ref-palette-neutral99) / <alpha-value>)',
					100: 'rgb(var(--md-ref-palette-neutral100) / <alpha-value>)',
				},

				'palette-neutral-variant': {
					0: 'rgb(var(--md-ref-palette-neutral-variant0) / <alpha-value>)',
					10: 'rgb(var(--md-ref-palette-neutral-variant10) / <alpha-value>)',
					20: 'rgb(var(--md-ref-palette-neutral-variant20) / <alpha-value>)',
					30: 'rgb(var(--md-ref-palette-neutral-variant30) / <alpha-value>)',
					40: 'rgb(var(--md-ref-palette-neutral-variant40) / <alpha-value>)',
					50: 'rgb(var(--md-ref-palette-neutral-variant50) / <alpha-value>)',
					60: 'rgb(var(--md-ref-palette-neutral-variant60) / <alpha-value>)',
					70: 'rgb(var(--md-ref-palette-neutral-variant70) / <alpha-value>)',
					80: 'rgb(var(--md-ref-palette-neutral-variant80) / <alpha-value>)',
					90: 'rgb(var(--md-ref-palette-neutral-variant90) / <alpha-value>)',
					95: 'rgb(var(--md-ref-palette-neutral-variant95) / <alpha-value>)',
					99: 'rgb(var(--md-ref-palette-neutral-variant99) / <alpha-value>)',
					100: 'rgb(var(--md-ref-palette-neutral-variant100) / <alpha-value>)',
				},
			},
			opacity: {
				'normal': '0.05',
				'hover': '0.08',
				'focus': '0.12',
				'disabled': '0.38',
				'disabledBg': '0.12',
				'elevationShadow1': '0.15',
				'elevationShadow2': '0.30'
			},
			boxShadow: {
				'elevation1': '0px 1px 3px 1px rgb(0 0 0 / 0.15), 0px 1px 2px 0px rgb(0 0 0 / 0.3)',
				'elevation2': '0px 2px 6px 2px rgb(0 0 0 / 0.15), 0px 1px 2px 0px rgb(0 0 0 / 0.3)',
			}
		},
	},
	plugins: [],
}
