# List of dependencies of the project

[versions]
pedestal = "2.1.0"
kotlin-vite = "0.3.2"

# CSS
tailwindcss = "3.4.0"
postcss = "8.4.33"
autoprefixer = "10.4.16"

[plugins]
vite = { id = "dev.opensavvy.vite.kotlin", version.ref = "kotlin-vite" }

[libraries]
pedestal-progress = { module = "dev.opensavvy.pedestal:progress", version.ref = "pedestal" }

[bundles]
