# List of dependencies of the project
# Dependencies shared between all projects based on the Playground are declared in playground.versions.toml

[versions]
compose = "1.5.2"
pedestal = "2.0.0"
kotlin-vite = "0.2.2"

# CSS
tailwindcss = "3.3.3"
postcss = "8.4.31"
autoprefixer = "10.4.16"

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
vite = { id = "dev.opensavvy.vite.kotlin", version.ref = "kotlin-vite" }

[libraries]
pedestal-progress = { module = "dev.opensavvy.pedestal:progress", version.ref = "pedestal" }

[bundles]
