# List of dependencies of the project

[versions]
pedestal = "2.1.0"
kotlin-vite = "0.3.6"
kotlin-js-resources = "0.1.3"

# CSS
tailwindcss = "3.4.1"
postcss = "8.4.35"
autoprefixer = "10.4.17"

[plugins]
vite = { id = "dev.opensavvy.vite.kotlin", version.ref = "kotlin-vite" }
resources-producer = { id = "dev.opensavvy.resources.producer", version.ref = "kotlin-js-resources" }
resources-consumer = { id = "dev.opensavvy.resources.consumer", version.ref = "kotlin-js-resources" }

[libraries]
pedestal-progress = { module = "dev.opensavvy.pedestal:progress", version.ref = "pedestal" }

[bundles]
