# List of dependencies of the project

[versions]
pedestal = "2.1.0"             # https://gitlab.com/opensavvy/pedestal/-/releases
kotlin-vite = "0.3.6"          # https://gitlab.com/opensavvy/automation/kotlin-vite/-/releases
kotlin-js-resources = "0.2.3"  # https://gitlab.com/opensavvy/automation/kotlin-js-resources/-/releases

[plugins]
vite = { id = "dev.opensavvy.vite.kotlin", version.ref = "kotlin-vite" }
resources-producer = { id = "dev.opensavvy.resources.producer", version.ref = "kotlin-js-resources" }
resources-consumer = { id = "dev.opensavvy.resources.consumer", version.ref = "kotlin-js-resources" }

[libraries]
pedestal-progress = { module = "dev.opensavvy.pedestal:progress", version.ref = "pedestal" }

[bundles]
