[versions]
kotlin = "1.9.10"
compose = "1.5.2"
pedestal = "2.0.0"
kotlin-vite = "0.2.2"

# CSS
tailwindcss = "3.3.3"
postcss = "8.4.31"
autoprefixer = "10.4.16"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
vite = { id = "dev.opensavvy.vite.kotlin", version.ref = "kotlin-vite" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

pedestal-progress = { module = "dev.opensavvy.pedestal:progress", version.ref = "pedestal" }

# To use existing plugins in convention plugins, we must also declare them as libraries
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-nexusPublish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.3.0" }
