package opensavvy.material3.tailwind.demo.utils

import androidx.compose.runtime.Composable
import opensavvy.material3.tailwind.actions.chips.ChipGroup
import opensavvy.material3.tailwind.actions.chips.FilterChip
import opensavvy.material3.theme.ColorScheme
import org.jetbrains.compose.web.dom.P
import org.jetbrains.compose.web.dom.Text

@Composable
fun SchemeSelector(
	current: ColorScheme,
	onSelect: (ColorScheme) -> Unit,
) = Section("Color scheme") {
	P { Text("With Material3, the color schemes are generated by using different tones of the same color palette.") }
	P { Text("Additionally, the 'System' color scheme automatically selects between light and dark depending on the browser's configuration.") }

	ChipGroup {
		for (scheme in ColorScheme.entries) {
			FilterChip(scheme.name, active = current == scheme, onToggle = { onSelect(scheme) })
		}
	}
}
